# Generated by Django 5.0.6 on 2025-07-04 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='frequencys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meters', models.FloatField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Frequency', models.FloatField()),
                ('Callsign_Station', models.CharField(max_length=10)),
                ('Modulation', models.CharField(max_length=3)),
                ('Analog_Digital', models.CharField(max_length=7)),
                ('Decoding_ft8_ft4_cw_etc', models.CharField(max_length=5)),
                ('Date', models.DateField()),
                ('Time', models.TextField()),
                ('frequencys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Station', to='station.frequencys')),
            ],
        ),
    ]
