# Generated by Django 5.0.6 on 2025-07-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='frequencys',
            new_name='meters',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='frequencys',
            new_name='meters',
        ),
    ]
