# Generated by Django 5.0.6 on 2025-07-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_rename_frequencys_meters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='Analog_Digital',
        ),
        migrations.AddField(
            model_name='station',
            name='Analog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='Digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='Time',
            field=models.TimeField(),
        ),
    ]
