# Generated by Django 5.0.6 on 2025-07-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_remove_station_analog_digital_station_analog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='Decoding_ft8_ft4_cw_etc',
        ),
        migrations.AddField(
            model_name='station',
            name='CW',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='FT4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='FT8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='RTTY',
            field=models.BooleanField(default=False),
        ),
    ]
