# Generated by Django 5.2.4 on 2025-07-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_rename_meters_to_band'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='meters',
            new_name='band',
        ),
    ]
