# Generated by Django 5.2.4 on 2025-07-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0006_rename_meters_band_band'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='Modulation',
        ),
        migrations.AddField(
            model_name='station',
            name='AM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='FM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='LSB',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='SSB',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='USB',
            field=models.BooleanField(default=False),
        ),
    ]
