# Generated by Django 5.2.4 on 2025-07-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0007_replace_modulation_with_boolean_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='C4FM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='DMR',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='DSTAR',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='FAX',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='FSK31',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='JT65',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='JT9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='SSTV',
            field=models.BooleanField(default=False),
        ),
    ]
