# Generated by Django 5.2.4 on 2025-07-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0008_update_decoding_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='RSV',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='station',
            name='TRS',
            field=models.CharField(default='', max_length=3),
        ),
    ]
