# Generated by Django 5.2.4 on 2025-07-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0009_station_rsv_station_trs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='RSV',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='station',
            name='TRS',
            field=models.CharField(max_length=3),
        ),
    ]
