# Generated by Django 5.0.6 on 2025-07-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0010_alter_station_rsv_alter_station_trs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='Callsign_Station',
            field=models.CharField(max_length=20, verbose_name='Callsign/Station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='Frequency',
            field=models.CharField(max_length=10, verbose_name='Frequency'),
        ),
    ]
