# Generated by Django 5.0.6 on 2025-07-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0013_alter_station_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='Frequency',
            field=models.CharField(max_length=12, verbose_name='Frequency'),
        ),
    ]
