# Generated by Django 5.2.4 on 2025-07-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0014_alter_station_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='TRS',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
