# Generated by Django 5.0.6 on 2025-07-26 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0015_alter_station_trs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'verbose_name': 'Μπάντα', 'verbose_name_plural': 'Μπάντες'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Σταθμός', 'verbose_name_plural': 'Σταθμοί'},
        ),
    ]
