# Generated by Django 5.0.6 on 2025-07-29 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0016_alter_band_options_alter_station_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='AM',
            field=models.BooleanField(default=False, verbose_name='AM'),
        ),
        migrations.AlterField(
            model_name='station',
            name='Analog',
            field=models.BooleanField(default=False, verbose_name='Analog'),
        ),
        migrations.AlterField(
            model_name='station',
            name='C4FM',
            field=models.BooleanField(default=False, verbose_name='C4FM'),
        ),
        migrations.AlterField(
            model_name='station',
            name='CW',
            field=models.BooleanField(default=False, verbose_name='CW'),
        ),
        migrations.AlterField(
            model_name='station',
            name='Callsign_Station',
            field=models.CharField(max_length=20, verbose_name='Callsign/Σταθμός'),
        ),
        migrations.AlterField(
            model_name='station',
            name='DMR',
            field=models.BooleanField(default=False, verbose_name='DMR'),
        ),
        migrations.AlterField(
            model_name='station',
            name='DSTAR',
            field=models.BooleanField(default=False, verbose_name='DSTAR'),
        ),
        migrations.AlterField(
            model_name='station',
            name='Date',
            field=models.DateField(verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='station',
            name='Digital',
            field=models.BooleanField(default=False, verbose_name='Digital'),
        ),
        migrations.AlterField(
            model_name='station',
            name='FAX',
            field=models.BooleanField(default=False, verbose_name='FAX'),
        ),
        migrations.AlterField(
            model_name='station',
            name='FM',
            field=models.BooleanField(default=False, verbose_name='FM'),
        ),
        migrations.AlterField(
            model_name='station',
            name='FSK31',
            field=models.BooleanField(default=False, verbose_name='FSK31'),
        ),
        migrations.AlterField(
            model_name='station',
            name='FT4',
            field=models.BooleanField(default=False, verbose_name='FT4'),
        ),
        migrations.AlterField(
            model_name='station',
            name='FT8',
            field=models.BooleanField(default=False, verbose_name='FT8'),
        ),
        migrations.AlterField(
            model_name='station',
            name='Frequency',
            field=models.CharField(max_length=12, verbose_name='Συχνότητα'),
        ),
        migrations.AlterField(
            model_name='station',
            name='JT65',
            field=models.BooleanField(default=False, verbose_name='JT65'),
        ),
        migrations.AlterField(
            model_name='station',
            name='JT9',
            field=models.BooleanField(default=False, verbose_name='JT9'),
        ),
        migrations.AlterField(
            model_name='station',
            name='LSB',
            field=models.BooleanField(default=False, verbose_name='LSB'),
        ),
        migrations.AlterField(
            model_name='station',
            name='RSV',
            field=models.CharField(max_length=3, verbose_name='RSV'),
        ),
        migrations.AlterField(
            model_name='station',
            name='RTTY',
            field=models.BooleanField(default=False, verbose_name='RTTY'),
        ),
        migrations.AlterField(
            model_name='station',
            name='SSB',
            field=models.BooleanField(default=False, verbose_name='SSB'),
        ),
        migrations.AlterField(
            model_name='station',
            name='SSTV',
            field=models.BooleanField(default=False, verbose_name='SSTV'),
        ),
        migrations.AlterField(
            model_name='station',
            name='TRS',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='TRS'),
        ),
        migrations.AlterField(
            model_name='station',
            name='Time',
            field=models.TimeField(verbose_name='Ώρα'),
        ),
        migrations.AlterField(
            model_name='station',
            name='USB',
            field=models.BooleanField(default=False, verbose_name='USB'),
        ),
        migrations.AlterField(
            model_name='station',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Station', to='station.band', verbose_name='Μπάντα'),
        ),
    ]
