# Generated by Django 5.0.6 on 2025-07-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0017_alter_station_am_alter_station_analog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='Callsign_Station',
            field=models.CharField(max_length=50, verbose_name='Callsign/Σταθμός'),
        ),
    ]
