# Generated by Django 5.0.6 on 2025-07-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0018_alter_station_callsign_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='Callsign_Station',
            field=models.CharField(max_length=20, verbose_name='Callsign/Σταθμός'),
        ),
    ]
